#pragma once
#include<iostream>
#include<glad/glad.h>
#include<GLFW/glfw3.h>
class Shader
{
private:
	
	//fragementShader and vertex Shader's directory
	std::string fragDir, vertDir;
	//programID: to reference the shaderProgram generated by a call to compileShader
	GLuint programID;

	char** readShaderFile(std::string,unsigned int&);
	bool compileShader();
	void addShader(char** shaderCode, GLuint shaderID,GLuint codeLen,GLenum shaderType);
	void freeCodePointer(GLchar**,unsigned int);
	
public:
	Shader(std::string vertexShaderDir,std::string fragmentShaderDir);
	~Shader();
	void useShaderProgram();



};

