#pragma once
#include<iostream>
#include<functional>
#include<glad/glad.h>
#include<GLFW/glfw3.h>
class Shader
{
private:
	
	//fragementShader and vertex Shader's directory
	std::string fragDir, vertDir;
	//programID: to reference the shaderProgram generated by a call to compileShader
	GLuint programID;

	char** readShaderFile(std::string,unsigned int&);
	bool compileShader();
	void addShader(char** shaderCode, GLuint shaderID,GLuint codeLen,GLenum shaderType);
	void freeCodePointer(GLchar**,unsigned int);
	
public:
	Shader(std::string vertexShaderDir,std::string fragmentShaderDir);
	~Shader();
	void useShaderProgram();
	GLuint getUniformLocation(std::string varName) { return glGetUniformLocation(programID, varName.c_str()); }
	void setUniformInteger(std::string varName,GLint value) { glUniform1i(getUniformLocation(varName),value); };
	void setUniformMat4fv(std::string varName,GLint count,GLfloat *valuePtr) { glUniformMatrix4fv(getUniformLocation(varName),count,GL_FALSE,valuePtr); };
	std::function<void(GLuint)> callAfterUseProgram;



};

