#pragma once
#include<iostream>
#include<glad/glad.h>
#include<GLFW/glfw3.h>



class Window
{
protected:
	
private:
	
	//window intialization height and width
	int Height, Width;
	//render buffer dimensions. (usually updated every time using a callback function when the windows reasize event occurs)
	int bufferHeight, bufferWidth;

	std::string windowName;
	//window class to share opengl context with
	Window* share;
	//main GLFWwindow pointer.(generated by a call to create window)
	GLFWwindow* mainWindow;

	
public:
	Window(int height,int width,std::string,Window*);
	~Window();
	friend class Editor;
	

	int getBufferHeight() 
	{
		//get windows buffer Height
		glfwGetFramebufferSize(mainWindow, &bufferWidth, &bufferHeight); 
		return bufferHeight; 
	};
	int getBufferWidth() 
	{
		//get windows buffer width
		glfwGetFramebufferSize(mainWindow, &bufferWidth, &bufferHeight); 
		return bufferWidth; 
	};

	bool Window::shouldWindowClose()
	{
		//returns true if windows close event has occured
		if (mainWindow)
			return glfwWindowShouldClose(mainWindow);
		else
		{
			std::cerr << "ERROR::initialize window first!" << std::endl;
			return true;
		}
	}
	
	bool initialize();
	void setBufferSizeCallBackFunction(GLFWframebuffersizefun function);
	void swapBuffers() { glfwSwapBuffers(mainWindow); };
	void processInput();
	
};

