#pragma once
#include<functional>
#include<string>
#include<map>
#include"Math/EngineMath.h"
#include"Core/AkameCore.h"
class Shader
{
private:
	AKAME_API void ParseUniforms();
	std::map<std::string, unsigned int> uniformLocationMap;
	friend class Material;
	friend class DisplacementMap;
	//fragementShader and vertex Shader's directory
	std::string fragDir, vertDir,geoDir;
	//programID: to reference the shaderProgram generated by a call to compileShader
	unsigned int programID;

	AKAME_API char** readShaderFile(std::string,unsigned int&);
	AKAME_API bool compileShader();
	AKAME_API void addShader(char** shaderCode, unsigned int shaderID, unsigned int codeLen, unsigned int shaderType);
	AKAME_API void freeCodePointer(char**,unsigned int);
	AKAME_API void deleteProgram();
	friend class Material;
	friend class RenderingSystem;
	AKAME_API void setUniformMat4fv(unsigned int, unsigned int count, float* valuePtr);
public:
	AKAME_API Shader();
	AKAME_API Shader(std::string vertexShaderDir,std::string fragmentShaderDir,std::string geometryShaderDir);
	AKAME_API Shader(std::string vertexShaderDir,std::string fragmentShaderDir);
	
	AKAME_API void setShaderFileLocation(std::string vert, std::string frag) { vertDir = vert; fragDir = frag; };

	//functions for setting uniform variables
	AKAME_API unsigned int getUniformLocation(std::string varName);
	AKAME_API void setUniformInteger(std::string varName, unsigned int value);
	AKAME_API void setUniformInteger(unsigned int uniformLoc, unsigned int value);

	AKAME_API void setUniformVec3(std::string varName, const glm::vec3& vec);
	AKAME_API void setUniformMat4fv(std::string varName, unsigned int count, float* valuePtr);
	AKAME_API void setUniformMat4fvArray(std::string varName, unsigned int index, float* valuePtr);
	AKAME_API void setUniformFloat(std::string varName, float value);
	//call this to use this shader program
	AKAME_API void useShaderProgram();

	//will be called along with "useShaderProgram()"
	//std::function<void(GLuint)> callAfterUseProgram;
	
	AKAME_API ~Shader();
	

};

